// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWv_o35XmnO1rnyqpln5nynLFXNRUdReE',
    appId: '1:53919177278:web:e9991888e9bd9bc1ca4f6f',
    messagingSenderId: '53919177278',
    projectId: 'flutter-chat-app-f17fc',
    authDomain: 'flutter-chat-app-f17fc.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f17fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9dMlgYkDtucNO2BxpcDs9Pmc7KIcAIOA',
    appId: '1:53919177278:android:23458d7978e13e5dca4f6f',
    messagingSenderId: '53919177278',
    projectId: 'flutter-chat-app-f17fc',
    storageBucket: 'flutter-chat-app-f17fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSY-9CkgPh4ZFQbRB9REqU2SUlHDnhrHE',
    appId: '1:53919177278:ios:826834a803755437ca4f6f',
    messagingSenderId: '53919177278',
    projectId: 'flutter-chat-app-f17fc',
    storageBucket: 'flutter-chat-app-f17fc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSY-9CkgPh4ZFQbRB9REqU2SUlHDnhrHE',
    appId: '1:53919177278:ios:826834a803755437ca4f6f',
    messagingSenderId: '53919177278',
    projectId: 'flutter-chat-app-f17fc',
    storageBucket: 'flutter-chat-app-f17fc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWv_o35XmnO1rnyqpln5nynLFXNRUdReE',
    appId: '1:53919177278:web:833db0132eab414eca4f6f',
    messagingSenderId: '53919177278',
    projectId: 'flutter-chat-app-f17fc',
    authDomain: 'flutter-chat-app-f17fc.firebaseapp.com',
    storageBucket: 'flutter-chat-app-f17fc.appspot.com',
  );

}